input_vcf: 'EGAD00001002656.GATK.eye_var_path.vcf.gz'
aaf_change: '0.1'
family_name: ['B240001']
ped: '/home/mcgaugheyd/git/EGA_EGAD00001002656_NGS_reanalyze/EGAD00001002656.ped'
pick: 'all'
gemini_db_name: 'gemini_db/gnomad_faux.gemini.db'
samtools_version: 'samtools/1.6'
ref_genome: '/data/OGVFB/resources/human_g1k_v37_decoy.fasta'
VEP_version: 'VEP/90.8'
vcfanno_version: 'vcfanno/0.1.1'
vcfanno_lua: '/home/$USER/git/variant_prioritization/src/vcfanno_custom.lua'
vcfanno_conf: '/home/$USER/git/variant_prioritization/src/vcfanno_v2.conf'
vcf2db_version: 'vcf2db/7dfc48a'
gemini_version: 'gemini/0.20.1'
R_version: 'R/3.4.0_gcc-6.2.0'
pandoc_version: 'pandoc/1.15.0.6'
gemini_lenient: 'Yes'
regions: '/home/mcgaugheyd/git/variant_prioritization/src/vcf_region_split_100_coords.txt'
