input_vcf: 'homsy.benign.vcf.gz'
aaf_change: '0.1'
family_name: ""
ped: '/home/mcgaugheyd/git/eye_var_Pathogenicity/processed_data/faux.ped'
pick: 'all'
gemini_db_name: 'gemini_db/gnomad_faux.gemini.db'
samtools_version: 'samtools/1.6'
ref_genome: '/data/OGVFB/resources/human_g1k_v37_decoy.fasta'
VEP_version: 'VEP/92'
vcfanno_version: 'vcfanno/0.2.9'
vcfanno_lua: '/home/$USER/git/variant_prioritization/src/vcfanno_custom.lua'
vcfanno_conf: '/home/$USER/git/variant_prioritization/src/vcfanno_v2.conf'
vcf2db_version: 'vcf2db/2017.12.11'
gemini_version: 'gemini/0.20.1'
R_version: 'R/3.5'
pandoc_version: 'pandoc/2.1.1'
gemini_lenient: 'Yes'
regions: '/home/mcgaugheyd/git/variant_prioritization/src/vcf_region_split_100_coords.txt'
