input_vcf: 'clinvar_RD.vcf.gz'
aaf_change: '0.1'
family_name: ['FAUX']
ped: '/home/mcgaugheyd/git/eye_var_Pathogenicity/processed_data/faux.ped'
samtools_version: 'samtools/1.6'
ref_genome: '/data/OGVFB/resources/human_g1k_v37_decoy.fasta'
VEP_version: 'VEP/90.8'
vcfanno_version: 'vcfanno/0.1.1'
vcfanno_lua: '/home/$USER/git/variant_prioritization/src/vcfanno_custom.lua'
vcfanno_conf: '/home/$USER/git/variant_prioritization/src/vcfanno_v2.conf'
vcf2db_version: 'vcf2db/7dfc48a'
gemini_version: 'gemini/0.20.1'
R_version: 'R/3.4.0_gcc-6.2.0'
pandoc_version: 'pandoc/1.15.0.6'
regions: '/home/mcgaugheyd/git/variant_prioritization/src/vcf_region_split_100_coords.txt'
