---
title: "Model Assesement"
output: html_notebook
---
# Load trained models
From scripts/build_models.R run on biowulf2
```{r}
model_names <- names(my_models)[grepl('Fit',names(my_models))]
```


# ConfusionMatrix your model(s)
```{r}
library(tidyverse)
library(caret)
cm_maker <- function(model, data, cutoff=0.5) {
  new_predictions <- predict(model, data, type='prob') %>%
    mutate(Answers = data$Status, Prediction = case_when(Pathogenic > cutoff ~ 'Pathogenic', TRUE ~ 'NotPathogenic'))
  confusionMatrix(data = new_predictions$Prediction, reference = new_predictions$Answers, mode='prec_recall')
}

for (i in model_names){
  print(i)
  print(cm_maker(my_models[[i]], my_models$validate_set))
}
```


# AUC ROC
```{r, fig.width=5, fig.height=1.5}
library(PRROC)
library(cowplot)

# precision recall AUC
aucroc_maker <- function(model, data, cutoff=0.5) {
  new_predictions <- predict(model, data, type = 'prob') %>%
    mutate(Answers = data$Status, Prediction = case_when(Pathogenic > cutoff ~ 'Pathogenic', TRUE ~ 'NotPathogenic'))
  pr.curve(scores.class0 = new_predictions %>% filter(Answers=='Pathogenic') %>% pull(Pathogenic),
           scores.class1 = new_predictions %>% filter(Answers=='NotPathogenic') %>% pull(Pathogenic),
           curve = T)
}

# ROC AUC
roc_maker <- function(model, data, cutoff=0.5) {
  new_predictions <- predict(model, data, type = 'prob') %>%
    mutate(Answers = data$Status, Prediction = case_when(Pathogenic > cutoff ~ 'Pathogenic', TRUE ~ 'NotPathogenic'))
  roc.curve(scores.class0 = new_predictions %>% filter(Answers=='Pathogenic') %>% pull(Pathogenic),
           scores.class1 = new_predictions %>% filter(Answers=='NotPathogenic') %>% pull(Pathogenic),
           curve = T)
}

aucroc_data <- data.frame()
for (i in model_names){
  print(my_models[[i]]$method)
  aucroc <- aucroc_maker(my_models[[i]], my_models$validate_set)
  out <- aucroc$curve[,1:2] %>% data.frame()
  colnames(out) <- c('Recall','Precision')
  out$AUC <- aucroc$auc.integral
  out$model <- i
  out$'Model (AUC)' <- paste0(i, ' (',round(aucroc$auc.integral,2),')' )
  aucroc_data <- rbind(aucroc_data, out)
}

roc_data <- data.frame()
for (i in model_names){
  print(my_models[[i]]$method)
  roc <- roc_maker(my_models[[i]], my_models$validate_set)
  out <- roc$curve[,1:2] %>% data.frame()
  colnames(out) <- c('FPR','Sensitivity')
  out$model <- i
  out$AUC <- roc$auc
  out$'Model (AUC)' <- paste0(i, ' (',round(roc$auc, 2),')' )
  roc_data <- rbind(roc_data, out)
}

pr <- aucroc_data %>% ggplot(aes(x=Recall, y=Precision, colour=`Model (AUC)`)) + geom_line() + theme_minimal() + ggtitle('Precision Recall Curve')
roc <- roc_data %>% ggplot(aes(x=FPR, y=Sensitivity, colour=`Model (AUC)`)) + geom_line() + theme_minimal()  + ggtitle('ROC')

cowplot::plot_grid(roc, pr)
```
